### ISSUE TITLE
Docs: 모델 학습

### ISSUE THREAD

**Issue by rapidrabbit76** [rapidrabbit76/Classification-For-Everyone#15]
@zkdlfrlwl2 
각자 만든 모델 학습 시켜서 wandb report로 만드는 건 어떨까? 
시간이 걸리더라도 천천히 학습 시켜서 만들어 보려는데 ? 

# Discussion
wandb report 를

1.  데이터 셋 기준으로 할지
2. 모델 기준으로 모든 데이터에 대한 리포트를 만들지 
3. 1, 2 로 해서 모든 걸 합친 리포트를 만들지 

의견을 부탁합니다. 

---
학습 완료하면 학습 모델 별로 테그 달아서 main에 올리자 
다른 좋은 방법이 있으면 의견을 부탁합니다.

**Comment by zkdlfrlwl2** [comment]
wandb report 공식 소개 영상 보니까 진짜 보고서 형식이네. 근데 이거 익숙해지면 회사 보고서 쓸 때, 유용하게 활용할 수 있겠는데 ? 뭐 회사가 wandb 쓴다는 전제하에, **wandb report 사용해보는 건 찬성**.

어차피 모델 학습은 sweep으로 돌릴거니까 hpo에 대한 스트레스는 덜 할 것 같고 데이터 셋 기준으로 하면 report 쓸 내용이 빈약해질 것 같고 모델 기준으로 모든 데이터에 대한 report 만드는게 괜찮을 듯.

한 모델 당 넉넉잡아 2~3주 걸린다고 생각하면 되려나 ? 

report는 개인이 쓰고 싶은 내용을 자유롭게 기술하는 식으로 할 꺼 ? 아니면 미리 template을 만들어서 각 모델 별 내용만 바꾸고 전체적인 틀은 동일하게 ? 

같은 주제로 report 쓰는거니까 template를 미리 정해두고 하는게 좋을 듯.

**Comment by rapidrabbit76** [comment]
> wandb report 공식 소개 영상 보니까 진짜 보고서 형식이네. 근데 이거 익숙해지면 회사 보고서 쓸 때, 유용하게 활용할 수 있겠는데 ? 뭐 회사가 wandb 쓴다는 전제하에, **wandb report 사용해보는 건 찬성**.
> 
> 어차피 모델 학습은 sweep으로 돌릴거니까 hpo에 대한 스트레스는 덜 할 것 같고 데이터 셋 기준으로 하면 report 쓸 내용이 빈약해질 것 같고 모델 기준으로 모든 데이터에 대한 report 만드는게 괜찮을 듯.
> 
> 한 모델 당 넉넉잡아 2~3주 걸린다고 생각하면 되려나 ?
> 
> report는 개인이 쓰고 싶은 내용을 자유롭게 기술하는 식으로 할 꺼 ? 아니면 미리 template을 만들어서 각 모델 별 내용만 바꾸고 전체적인 틀은 동일하게 ?
> 
> 같은 주제로 report 쓰는거니까 template를 미리 정해두고 하는게 좋을 듯.

ㅇㅇ template 하나 만들어 줄 수 있을까? 요즘 나보다 시간 많으니 막 부탁하네 ㅋㅋㅋ
wandb 팀은 생성했으니까 거기에 실험 데이터 모아 놓고 각 모델별로 내용을 채워 보자 
template 만들고 들어갈 내용 헤딩만 처리해서 공유해줘 
모델 학습 끝날 때 까지는 이슈 유지할 게

**Comment by rapidrabbit76** [comment]
@zkdlfrlwl2 
이번주 모델 중복 제거 할때 report 작업좀 부탁할게 
노션에 리펙토링 kanban에 report 추가해줘

**Comment by zkdlfrlwl2** [comment]
> @zkdlfrlwl2 이번주 모델 중복 제거 할때 report 작업좀 부탁할게 노션에 리펙토링 kanban에 report 추가해줘

ㅇㅋㅇㅋ 다른 사람은 어떻게 했나 갤러리 참고하면서 초안 만들어볼게

**Comment by rapidrabbit76** [comment]
@zkdlfrlwl2 
이번주 모델 중복 제거 할때 report 작업좀 부탁할게 
노션에 리펙토링 kanban에 report  추가해줘
