### ISSUE TITLE
Test: Github Actions 활용한 pytest 자동화

### ISSUE THREAD

**Issue by zkdlfrlwl2** [rapidrabbit76/Classification-For-Everyone#18]
새로운 모델 구현 or 기존 모델 수정 후 테스트 자동화를 위해 Github Actions 사용하기

### 작업 순서 
1. Github Actions Test용 test branch 생성
2. .github/workflows/CI.yaml 디렉토리 생성
3. CI.yaml 파일 작성
4. CI.yaml 파일 작성 후 모델 1개씩 push 하면서 제대로 작동하는지 체크

---------------------

대충 이렇게 진행 해보려는 데 다른 의견 있으면 코멘트 부탁 @rapidrabbit76

**Comment by rapidrabbit76** [comment]
1. test branch를 생성해야해?

**Comment by zkdlfrlwl2** [comment]
refactor branch에서 .github 디렉토리 만들고 해도 되는데 그래도 새로운 기능 추가하는거니까 branch 따로 생성했다가 잘 돌아가는거 확인되면 merge 하는게 어떰 ?

**Comment by rapidrabbit76** [comment]
올리면 자동으로 테스트 도는게 좋을꺼 같은데?? 

테스트 통과 안하면 merge 안되게 가능할껄 

Pr 날리거나 push 하면 테스트 돌게 해서 실패하면 안되게 할 수 있지 않아??

**Comment by zkdlfrlwl2** [comment]
내가 github actions에 익숙하지가 않아서 따로 branch 판 다음에 이것 저것 만져보고 의도대로 동작하는게 확인되면 refactor branch로 merge 해서 그 이후에 refactor branch에 push or PR 확인되면 테스트 돌게끔 하려고 했지.

저렇게 기본 골자 잡고 나서 테스트 돌릴 항목 더 늘려 나가는 것도 괜찮을 것 같고

**Comment by rapidrabbit76** [comment]
아 그런거면 괜찮을거 같다. ㅇㅇ

**Comment by zkdlfrlwl2** [comment]
일단 나는 wandb report template이랑 저 github actions 작업하고 있을게 

나도 자동화엔 관심이 좀 있어서 이 참에 만져보려고 

자동화 잘 해 놓으면 일이 줄잖아 

일이 줄면 인생이 행복해지지 

이번 기회에 github actions & pytest  해보면서 익혀볼게

좀 늦더라도 양해 부탁

**Comment by rapidrabbit76** [comment]
> 

얼마든지 

고맙습니다. 
작업 하면서 notion에 작업과정 문서로 만들어주면 나도 해볼게

**Comment by zkdlfrlwl2** [comment]
오케이 notion으로 정리하면서 해볼게
