### ISSUE TITLE
new config(hyperparameters) management way 

### ISSUE THREAD

**Issue by rapidrabbit76** [rapidrabbit76/Classification-For-Everyone#5]
@zkdlfrlwl2 

PL Module 내부에 save_hyperparameters 좀 까봤는데 이거 EasyDict 모듈 던져 넣어도 내부에 hyperparameter 전부 접근 가능하고 로깅을 하네 

다음 refactoring때 이거 반영해서 하려는데 어떰? 

```python

class TestPLModule(pl.LightningModule):

    def __init__(self, params):
        super().__init__()
        # manually assign single argument
        self.save_hyperparameters(params)

        print(self.hparams.image_size)
        print(self.hparams.torchscript_model_save_path)
        print(self.hparams.hparams.lr)

    def forward(self, x):
        return 0


config = utils.get_config()
model = TestPLModule(config)

```

**Comment by rapidrabbit76** [comment]
사실 지금 방식이 편할꺼라고 생각하고 PL 깊은 이해 없이 나중에 한번에 수정하자는 생각으로 대충 짠거였거든 
하다보니 보기가 너무 싫어서 개선방안을 고민하다.
실험 해 봤는데 가능하네

**Comment by zkdlfrlwl2** [comment]
> 사실 지금 방식이 편할꺼라고 생각하고 PL 깊은 이해 없이 나중에 한번에 수정하자는 생각으로 대충 짠거였거든 하다보니 보기가 너무 싫어서 개선방안을 고민하다. 실험 해 봤는데 가능하네

config.yaml에 parameter랑 hyper-parameter 다 욱여넣어서 최종 모델 생성자 파라미터로 넘겨주자는거네. self.save_hyperparameters() 하면 wandb_logger.experiment.config.update() 안해도 다 로깅된다는 소리 ?

**Comment by rapidrabbit76** [comment]
wandb 쪽은 아직 확인안했는데 save_hyperparameters 하면 전부 로깅되지 않음? 
sweep 돌리거나 할때 테이블에 전부 뜨던데

**Comment by zkdlfrlwl2** [comment]
pytorch lightning wandblogger 쪽 설명 보니까 save_hyperparameters 하면 저장되는 것 같네. wandb_logger.experiment.config.update() <- 이거는 새로운 hyper-parameter 저장할 때 dict 넘겨주면 되는거고. 그럼 우린 parameter나 hyper-parameter 다 config.yaml에 작성할거니까 뒤에 update는 지워도 되겠네.

**Comment by rapidrabbit76** [comment]
> > 사실 지금 방식이 편할꺼라고 생각하고 PL 깊은 이해 없이 나중에 한번에 수정하자는 생각으로 대충 짠거였거든 하다보니 보기가 너무 싫어서 개선방안을 고민하다. 실험 해 봤는데 가능하네
> 
> config.yaml에 parameter랑 hyper-parameter 다 욱여넣어서 최종 모델 생성자 파라미터로 넘겨주자는거네. 

이건 맞음 가능한 확인하고 수정하는 파일수를 줄이고 싶거든 
나중엔 PL Trainer 하나만 놓고 모델만 바꿔서 실험 가능하게 코드를 전부 고치려고 해서 

config.yaml 안에 

- 실험 환경설정 
- 데이터 모듈 설정 
- 학습모델 설정

전부 넣어 놓고 돌릴 수 있게 하고 싶어서

어짜피 각 PL module 안에는 self.hparams 으로 접근하니깐 불필요한 param 이 있든 없든 통합이 가능할거 같아서

**Comment by zkdlfrlwl2** [comment]
그럼 최종 디렉토리 구조가 root에 data directory, datamodule directory, config.yaml, train.py, AlexNet directory, VGG directory ... 이렇게 해서 config.yaml의 모델 path만 수정해서 바로 돌릴 수 있게 ?

**Comment by rapidrabbit76** [comment]
> 그럼 최종 디렉토리 구조가 root에 data directory, datamodule directory, config.yaml, train.py, AlexNet directory, VGG directory ... 이렇게 해서 config.yaml의 모델 path만 수정해서 바로 돌릴 수 있게 ?

최종 디렉터리 구조는 조금 더 생각해 볼려고 
PL module 을 보관하는 python package를 하나 놓고 루트에 있는 trainer 에서 package 내부에 있는 PL module만 가져와서 돌릴 수 있도록

나중에 이글 수정해서 대략적인 구조를 다시 올릴게

**Comment by rapidrabbit76** [comment]
@zkdlfrlwl2 

#9 리펙토링 하는거 참고 부탁 이거 리뷰 하고 넘어가자
